### ISSUE TITLE
8.0.1 compatibility

### ISSUE THREAD

**Issue by mitchellwrosen** [chrisdone/present#4]
Would be nice to have 8.0.1 compatibility for this package.

**Comment by jowens** [comment]
Presuming this is the same issue; a fresh install of slack fails on installing present.

```
--  While building package present-4.0.2 using:
      /Users/jowens/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/jowens/.stack/global-project/.stack-work/logs/present-4.0.2.log

    Configuring present-4.0.2...
    Building present-4.0.2...
    Preprocessing library present-4.0.2...
    [1 of 2] Compiling Control.Monad.Trans.State.Strict ( src/Control/Monad/Trans/State/Strict.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Trans/State/Strict.o )
    [2 of 2] Compiling Present          ( src/Present.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Present.o )

    /private/var/folders/wn/2ppvrfkd7g18c3k5gsjq6b900000gn/T/stack12444/present-4.0.2/src/Present.hs:303:18: error:
        â¢ The constructor âDataDâ should have 6 arguments, but has been given 5
        â¢ In the pattern: DataD _cxt _ vars cons _deriving
          In a case alternative:
              DataD _cxt _ vars cons _deriving
                -> do { cs <- mapM makeConstructor cons;
                        return
                          (Just
                             (DataTypeDefinition
                                typeConstructor (DataType (map toTypeVariable vars) cs))) }
          In the expression:
            case dec of {
              DataD _cxt _ vars cons _deriving
                -> do { cs <- mapM makeConstructor cons;
                        return
                          (Just
                             (DataTypeDefinition
                                typeConstructor (DataType (map toTypeVariable vars) cs))) }
              NewtypeD _cxt _ vars con _deriving
                -> do { c <- makeConstructor con;
                        return
                          (Just
                             (DataTypeDefinition
                                typeConstructor (DataType (map toTypeVariable vars) [...]))) }
              TySynD _ vars ty
                -> do { ty' <- normalizeType ty;
                        return
                          (Just
                             (TypeAliasDefinition
                                typeConstructor (TypeAlias (map toTypeVariable vars) ty'))) }
              _ -> fail "Not a supported data type declaration." }

    /private/var/folders/wn/2ppvrfkd7g18c3k5gsjq6b900000gn/T/stack12444/present-4.0.2/src/Present.hs:952:40: error:
        â¢ The constructor âInstanceDâ should have 4 arguments, but has been given 3
        â¢ In the pattern:
            InstanceD _ (AppT (ConT _className) (ConT typeName)) _
          In a case alternative:
              InstanceD _ (AppT (ConT _className) (ConT typeName)) _
                -> Just (TypeConstructor typeName, ValueVariable method)
          In the expression:
            case i of {
              InstanceD _ (AppT (ConT _className) (ConT typeName)) _
                -> Just (TypeConstructor typeName, ValueVariable method)
              _ -> Nothing }

    /private/var/folders/wn/2ppvrfkd7g18c3k5gsjq6b900000gn/T/stack12444/present-4.0.2/src/Present.hs:1025:14: error:
        â¢ The constructor âVarIâ should have 3 arguments, but has been given 4
        â¢ In the pattern: VarI _ ty _ _
          In the pattern: Just (VarI _ ty _ _)
          In a case alternative:
              Just (VarI _ ty _ _) -> makeTypePresenter (return ty)
```

**Comment by mitchellwrosen** [comment]
@jowens Yep. Though, you should be able to just compile with 7.10. On stack that'd be with resolver `lts-6`

**Comment by jowens** [comment]
@mitchellwrosen Understood. I am hopeful, though, that useful packages like this will work straight out of the box (with a vanilla stack install), especially for new-ish users (like me) for whom the learning curve is steep. (I switched to stack simply because installing what I needed/wanted standalone was pretty daunting, and stack mostly works, but wouldn't it be nice if it wholly worked in cases like this one?)

FWIW I am hoping to install the packages here—https://github.com/serras/emacs-haskell-tutorial/blob/master/tutorial.md—which include present.

**Comment by mitchellwrosen** [comment]
@jowens You have a couple options. One is to set your global stack project's resolver (~/.stack/global-project/stack.yaml) to some flavor of ghc 7.10 - that'd be either `lts-6` or `ghc-7.10`. Then, a vanilla `stack install present` should work.

Otherwise, you can use `stack install present --resolver XXX` to override the global project's settings (again, with `lts-6` or `ghc-7.10`)

**Comment by jowens** [comment]
Thank you! I'll try that.

**Comment by sjakobi** [comment]
I've started to work on this on my [ghc-8.0 branch](https://github.com/sjakobi/present/tree/ghc-8.0). This is pretty much my first encounter with TemplateHaskell so if anyone wants to point me at some great TemplateHaskell resources, please do so!

Of course I don't want to break compatibility with GHC-7.10 so I'll have to add a bunch of CPP in the end…

**Comment by chrisdone** [comment]
@sjakobi that sounds good. I'll merge a PR with CPP to handle both 7.10 and 8.0.

**Comment by sjakobi** [comment]
The changes from #5 have been released with v4.1.0.
